//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 10:27:24 PM CET 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accountNumber complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="accountNumber">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ibanNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="localNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accountNumber", propOrder = {
    "id",
    "ibanNumber",
    "localNumber"
})
public class AccountNumber {

  protected long id;
  @XmlElement(required = true)
  protected String ibanNumber;
  @XmlElement(required = true)
  protected String localNumber;

  /**
   * Gets the value of the id property.
   */
  public long getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the ibanNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getIbanNumber() {
    return ibanNumber;
  }

  /**
   * Sets the value of the ibanNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setIbanNumber(String value) {
    this.ibanNumber = value;
  }

  /**
   * Gets the value of the localNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getLocalNumber() {
    return localNumber;
  }

  /**
   * Sets the value of the localNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLocalNumber(String value) {
    this.localNumber = value;
  }

}
