//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.12 at 06:16:38 PM CET 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeleteInvoiceResponse_QNAME = new QName("http://spring.io/guides/gs-producing-web-service", "deleteInvoiceResponse");
    private final static QName _GetAllInvoicesRequest_QNAME = new QName("http://spring.io/guides/gs-producing-web-service", "getAllInvoicesRequest");
    private final static QName _UpdateInvoiceResponse_QNAME = new QName("http://spring.io/guides/gs-producing-web-service", "updateInvoiceResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetInvoiceByNumberRequest }
     * 
     */
    public GetInvoiceByNumberRequest createGetInvoiceByNumberRequest() {
        return new GetInvoiceByNumberRequest();
    }

    /**
     * Create an instance of {@link GetInvoiceByIdRequest }
     * 
     */
    public GetInvoiceByIdRequest createGetInvoiceByIdRequest() {
        return new GetInvoiceByIdRequest();
    }

    /**
     * Create an instance of {@link AddInvoiceResponse }
     * 
     */
    public AddInvoiceResponse createAddInvoiceResponse() {
        return new AddInvoiceResponse();
    }

    /**
     * Create an instance of {@link InvoiceXml }
     * 
     */
    public InvoiceXml createInvoiceXml() {
        return new InvoiceXml();
    }

    /**
     * Create an instance of {@link GetAllInvoicesResponse }
     * 
     */
    public GetAllInvoicesResponse createGetAllInvoicesResponse() {
        return new GetAllInvoicesResponse();
    }

    /**
     * Create an instance of {@link DeleteInvoiceRequest }
     * 
     */
    public DeleteInvoiceRequest createDeleteInvoiceRequest() {
        return new DeleteInvoiceRequest();
    }

    /**
     * Create an instance of {@link AddInvoiceRequest }
     * 
     */
    public AddInvoiceRequest createAddInvoiceRequest() {
        return new AddInvoiceRequest();
    }

    /**
     * Create an instance of {@link UpdateInvoiceRequest }
     * 
     */
    public UpdateInvoiceRequest createUpdateInvoiceRequest() {
        return new UpdateInvoiceRequest();
    }

    /**
     * Create an instance of {@link GetInvoiceByIdResponse }
     * 
     */
    public GetInvoiceByIdResponse createGetInvoiceByIdResponse() {
        return new GetInvoiceByIdResponse();
    }

    /**
     * Create an instance of {@link GetInvoiceByNumberResponse }
     * 
     */
    public GetInvoiceByNumberResponse createGetInvoiceByNumberResponse() {
        return new GetInvoiceByNumberResponse();
    }

    /**
     * Create an instance of {@link CompanyXml }
     * 
     */
    public CompanyXml createCompanyXml() {
        return new CompanyXml();
    }

    /**
     * Create an instance of {@link InvoiceEntryXml }
     * 
     */
    public InvoiceEntryXml createInvoiceEntryXml() {
        return new InvoiceEntryXml();
    }

    /**
     * Create an instance of {@link AccountNumberXml }
     * 
     */
    public AccountNumberXml createAccountNumberXml() {
        return new AccountNumberXml();
    }

    /**
     * Create an instance of {@link AddressXml }
     * 
     */
    public AddressXml createAddressXml() {
        return new AddressXml();
    }

    /**
     * Create an instance of {@link ContactDetailsXml }
     * 
     */
    public ContactDetailsXml createContactDetailsXml() {
        return new ContactDetailsXml();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://spring.io/guides/gs-producing-web-service", name = "deleteInvoiceResponse")
    public JAXBElement<Object> createDeleteInvoiceResponse(Object value) {
        return new JAXBElement<Object>(_DeleteInvoiceResponse_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://spring.io/guides/gs-producing-web-service", name = "getAllInvoicesRequest")
    public JAXBElement<Object> createGetAllInvoicesRequest(Object value) {
        return new JAXBElement<Object>(_GetAllInvoicesRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://spring.io/guides/gs-producing-web-service", name = "updateInvoiceResponse")
    public JAXBElement<Object> createUpdateInvoiceResponse(Object value) {
        return new JAXBElement<Object>(_UpdateInvoiceResponse_QNAME, Object.class, null, value);
    }

}
