//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 09:53:45 PM CET 
//


package modelForSOAP;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for company complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="company">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taxIdentificationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accountNumber" type="{http://spring.io/guides/gs-producing-web-service}accountNumber"/>
 *         &lt;element name="contactDetails" type="{http://spring.io/guides/gs-producing-web-service}contactDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "company", propOrder = {
    "id",
    "name",
    "taxIdentificationNumber",
    "accountNumber",
    "contactDetails"})
public class Company {

  protected long id;
  @XmlElement(required = true)
  protected String name;
  @XmlElement(required = true)
  private String taxIdentificationNumber;
  @XmlElement(required = true)
  private AccountNumber accountNumber;
  @XmlElement(required = true)
  private ContactDetails contactDetails;

  /**
   * Gets the value of the id property.
   */
  public long getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the taxIdentificationNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getTaxIdentificationNumber() {
    return taxIdentificationNumber;
  }

  /**
   * Sets the value of the taxIdentificationNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTaxIdentificationNumber(String value) {
    this.taxIdentificationNumber = value;
  }

  /**
   * Gets the value of the accountNumber property.
   *
   * @return possible object is {@link AccountNumber }
   */
  public AccountNumber getAccountNumber() {
    return accountNumber;
  }

  /**
   * Sets the value of the accountNumber property.
   *
   * @param value allowed object is {@link AccountNumber }
   */
  public void setAccountNumber(AccountNumber value) {
    this.accountNumber = value;
  }

  /**
   * Gets the value of the contactDetails property.
   *
   * @return possible object is {@link ContactDetails }
   */
  public ContactDetails getContactDetails() {
    return contactDetails;
  }

  /**
   * Sets the value of the contactDetails property.
   *
   * @param value allowed object is {@link ContactDetails }
   */
  public void setContactDetails(ContactDetails value) {
    this.contactDetails = value;
  }

}
