//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 09:53:45 PM CET 
//


package modelForSOAP;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for invoiceEntry complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="invoiceEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="vatValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="grossValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="vatRate" type="{http://spring.io/guides/gs-producing-web-service}vat"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invoiceEntry", propOrder = {
    "id",
    "item",
    "quantity",
    "price",
    "vatValue",
    "grossValue",
    "vatRate"})
public class InvoiceEntry {

  protected long id;
  @XmlElement(required = true)
  private String item;
  private long quantity;
  @XmlElement(required = true)
  private BigDecimal price;
  @XmlElement(required = true)
  private BigDecimal vatValue;
  @XmlElement(required = true)
  private BigDecimal grossValue;
  @XmlElement(required = true)
  private Vat vatRate;

  /**
   * Gets the value of the id property.
   */
  public long getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the item property.
   *
   * @return possible object is {@link String }
   */
  public String getItem() {
    return item;
  }

  /**
   * Sets the value of the item property.
   *
   * @param value allowed object is {@link String }
   */
  public void setItem(String value) {
    this.item = value;
  }

  /**
   * Gets the value of the quantity property.
   */
  public long getQuantity() {
    return quantity;
  }

  /**
   * Sets the value of the quantity property.
   */
  public void setQuantity(long value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the price property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getPrice() {
    return price;
  }

  /**
   * Sets the value of the price property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setPrice(BigDecimal value) {
    this.price = value;
  }

  /**
   * Gets the value of the vatValue property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getVatValue() {
    return vatValue;
  }

  /**
   * Sets the value of the vatValue property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setVatValue(BigDecimal value) {
    this.vatValue = value;
  }

  /**
   * Gets the value of the grossValue property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getGrossValue() {
    return grossValue;
  }

  /**
   * Sets the value of the grossValue property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setGrossValue(BigDecimal value) {
    this.grossValue = value;
  }

  /**
   * Gets the value of the vatRate property.
   *
   * @return possible object is {@link Vat }
   */
  public Vat getVatRate() {
    return vatRate;
  }

  /**
   * Sets the value of the vatRate property.
   *
   * @param value allowed object is {@link Vat }
   */
  public void setVatRate(Vat value) {
    this.vatRate = value;
  }

}
