//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 09:53:45 PM CET 
//


package modelForSOAP;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for invoice complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="invoice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="issueDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="totalNetValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalGrossValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="seller" type="{http://spring.io/guides/gs-producing-web-service}company"/>
 *         &lt;element name="buyer" type="{http://spring.io/guides/gs-producing-web-service}company"/>
 *         &lt;element name="entries" type="{http://spring.io/guides/gs-producing-web-service}invoice" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invoice", propOrder = {
    "id",
    "number",
    "issueDate",
    "dueDate",
    "totalNetValue",
    "totalGrossValue",
    "seller",
    "buyer",
    "entries"})
public class Invoice {

  protected long id;
  @XmlElement(required = true)
  protected String number;
  @XmlElement(required = true)
  @XmlSchemaType(name = "date")
  private XMLGregorianCalendar issueDate;
  @XmlElement(required = true)
  @XmlSchemaType(name = "date")
  private XMLGregorianCalendar dueDate;
  @XmlElement(required = true)
  private BigDecimal totalNetValue;
  @XmlElement(required = true)
  private BigDecimal totalGrossValue;
  @XmlElement(required = true)
  private Company seller;
  @XmlElement(required = true)
  private Company buyer;
  @XmlElement(required = true)
  private List<Invoice> entries;

  /**
   * Gets the value of the id property.
   */
  public long getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the number property.
   *
   * @return possible object is {@link String }
   */
  public String getNumber() {
    return number;
  }

  /**
   * Sets the value of the number property.
   *
   * @param value allowed object is {@link String }
   */
  public void setNumber(String value) {
    this.number = value;
  }

  /**
   * Gets the value of the issueDate property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getIssueDate() {
    return issueDate;
  }

  /**
   * Sets the value of the issueDate property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setIssueDate(XMLGregorianCalendar value) {
    this.issueDate = value;
  }

  /**
   * Gets the value of the dueDate property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDueDate() {
    return dueDate;
  }

  /**
   * Sets the value of the dueDate property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setDueDate(XMLGregorianCalendar value) {
    this.dueDate = value;
  }

  /**
   * Gets the value of the totalNetValue property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getTotalNetValue() {
    return totalNetValue;
  }

  /**
   * Sets the value of the totalNetValue property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setTotalNetValue(BigDecimal value) {
    this.totalNetValue = value;
  }

  /**
   * Gets the value of the totalGrossValue property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getTotalGrossValue() {
    return totalGrossValue;
  }

  /**
   * Sets the value of the totalGrossValue property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setTotalGrossValue(BigDecimal value) {
    this.totalGrossValue = value;
  }

  /**
   * Gets the value of the seller property.
   *
   * @return possible object is {@link Company }
   */
  public Company getSeller() {
    return seller;
  }

  /**
   * Sets the value of the seller property.
   *
   * @param value allowed object is {@link Company }
   */
  public void setSeller(Company value) {
    this.seller = value;
  }

  /**
   * Gets the value of the buyer property.
   *
   * @return possible object is {@link Company }
   */
  public Company getBuyer() {
    return buyer;
  }

  /**
   * Sets the value of the buyer property.
   *
   * @param value allowed object is {@link Company }
   */
  public void setBuyer(Company value) {
    this.buyer = value;
  }

  /**
   * Gets the value of the entries property.
   *
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the entries property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getEntries().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list {@link Invoice }
   */
  public List<Invoice> getEntries() {
    if (entries == null) {
      entries = new ArrayList<Invoice>();
    }
    return this.entries;
  }

}
